### ISSUE TITLE
Cartpole example not working

### ISSUE THREAD

**Issue by lcdbezerra** [Jianxun-Wang/PIMBRL#1]
When running:

`python cartpole.py`

After changing the Path to include the desired modules:

```
import sys
sys.path.insert(0, '/PATH_TO/PIMBRL')
sys.path.insert(0, '/PATH_TO/PIMBRL/src')
```

I  get the following error:

```
Traceback (most recent call last):
File "/PATH_TO/PIMBRL/examples/cartpole.py", line 34, in <module>
RL = TD3(**RLinp)
TypeError: __init__() got an unexpected keyword argument 'net_type'
```

**Package Version**

`python=3.9.7`

**Comment by Xin-yang-Liu** [comment]
Thank you for pointing this bug out. This bug is due to the outdated API. I have fixed it.

As we keep developing this package and may modify some interfaces, there may be more outdated APIs/misuse of modules. Please feel free to report the bugs here and I will try my best to fix them.
