### ISSUE TITLE
Initial conditions Kuramoto-Sivashinsky Equation

### ISSUE THREAD

**Issue by stweigand97** [Jianxun-Wang/PIMBRL#4]
Hi, I have a question concerning the initial conditions (ICs) of the Kuramoto-Sivashinsky (KS) control problem.

The paper states that the ICs are "sampled from the attractor of the unforced KS equation". How exactly are these starting conditions computed? In other words, how did you generate the [ks_init.tensor](https://github.com/Jianxun-Wang/PIMBRL/blob/main/ks_init.tensor) file?

**Comment by Xin-yang-Liu** [comment]
Hi Stefan,

We use the KS environment to generate the initial conditions. The KS environment defined in the file ```src/envs.py``` can be viewed as a finite difference solver and we use the exact same code (with 0 control actions, ```act=0```) to generate the ```ks_init.tensor```.

**Comment by stweigand97** [comment]
So the initial conditions are generated by running the solver starting from a solution set to zero and then not applying the forcing term (i.e. 0 control actions)? In other words, what are the initial conditions of the simulation to generate the attractor? What time period do the states in ``ks_init.tensor``represent?

Thanks a lot!

**Comment by Xin-yang-Liu** [comment]
The initial condition for generating this ```ks_init.tensor``` can actually be seen in the commented-out part (Line 229-235 in ```src/envs.py```). Basically, it is a linear combination of the sine basis. The initial value can be directly read from the first row of the ```ks_init.tensor```

**Comment by stweigand97** [comment]
Thanks for clarifying!
